# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud` CLI reference.

The commands below are regenerated by `poe docs-generate` from the Click command
tree; see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud-reference.md
   :start-line: 2
"""

from __future__ import annotations

from airbyte.cli.cloud import connections, destinations, jobs, sources, workspaces


__all__ = [
    "connections",
    "destinations",
    "jobs",
    "sources",
    "workspaces",
]
