# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud` CLI reference.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli_docs.py`.

.. include:: ../../../docs/generated/cli/cloud-reference.md
   :start-line: 2
"""

from __future__ import annotations

from airbyte.cli.cloud import connections, destinations, jobs, login, sources, workspaces
from airbyte.cli.cloud._cli import cloud_app


__all__ = [
    "cloud_app",
    "connections",
    "destinations",
    "jobs",
    "login",
    "sources",
    "workspaces",
]
