# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud connections` commands.

The commands below are regenerated by `poe docs-generate` from the Click command
tree; see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud/connections.md
   :start-line: 2
"""

from __future__ import annotations

import click

from airbyte._util import api_util
from airbyte.cli.cloud._api_helpers import connection_to_dict, get_auth_context, job_to_dict
from airbyte.cli.cloud._json_helpers import (
    JsonHelpCommand,
    JsonHelpGroup,
    error_json,
    json_output,
    register_schema,
    resolve_entity_id,
)


@click.group(cls=JsonHelpGroup)
@click.pass_context
def connections(ctx: click.Context) -> None:
    """Manage Airbyte connections."""
    pass


register_schema(
    "connections_list",
    description="List all connections in the workspace.",
    required_params={"workspace_id": "The workspace ID."},
)


@connections.command("list", cls=JsonHelpCommand)
@click.pass_context
def connections_list(ctx: click.Context) -> None:
    """List connections in the workspace."""
    api_url, client_id, client_secret, workspace_id = get_auth_context(ctx)
    results = api_util.list_connections(
        workspace_id=workspace_id,
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
    )
    json_output([connection_to_dict(c) for c in results])


register_schema(
    "connections_get",
    description="Get details of a specific connection.",
    required_params={
        "workspace_id": "The workspace ID.",
        "connection_id": "The connection ID to retrieve, as an argument or --connection-id.",
    },
)


@connections.command("get", cls=JsonHelpCommand)
@click.argument("connection_id_arg", required=False)
@click.option("--connection-id", default=None, help="The connection ID to retrieve.")
@click.pass_context
def connections_get(
    ctx: click.Context,
    connection_id_arg: str | None,
    connection_id: str | None,
) -> None:
    """Get details of a specific connection."""
    connection_id = resolve_entity_id(
        connection_id_arg,
        connection_id,
        option_name="--connection-id",
    )
    api_url, client_id, client_secret, workspace_id = get_auth_context(ctx)
    result = api_util.get_connection(
        workspace_id=workspace_id,
        connection_id=connection_id,
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
    )
    json_output(connection_to_dict(result))


register_schema(
    "connections_create",
    description="Create a new connection between a source and destination.",
    required_params={
        "workspace_id": "The workspace ID.",
        "name": "Display name for the connection.",
        "source_id": "The source ID.",
        "destination_id": "The destination ID.",
    },
    optional_params={
        "selected_stream_name": "Stream name to sync. Repeat for multiple streams.",
        "prefix": "Optional table prefix for destination.",
    },
)


@connections.command("create", cls=JsonHelpCommand)
@click.option("--name", required=True, help="Display name for the connection.")
@click.option("--source-id", required=True, help="The source ID.")
@click.option("--destination-id", required=True, help="The destination ID.")
@click.option("--selected-stream-name", multiple=True, help="Stream name to sync.")
@click.option("--prefix", default="", help="Optional table prefix for destination.")
@click.pass_context
def connections_create(
    ctx: click.Context,
    name: str,
    source_id: str,
    destination_id: str,
    selected_stream_name: tuple[str, ...],
    prefix: str,
) -> None:
    """Create a new connection."""
    api_url, client_id, client_secret, workspace_id = get_auth_context(ctx)
    result = api_util.create_connection(
        name=name,
        source_id=source_id,
        destination_id=destination_id,
        workspace_id=workspace_id,
        prefix=prefix,
        selected_stream_names=list(selected_stream_name),
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
    )
    json_output(connection_to_dict(result))


register_schema(
    "connections_rename",
    description="Rename a connection by ID.",
    required_params={
        "workspace_id": "The workspace ID.",
        "connection_id": "The connection ID to rename, as an argument or --connection-id.",
        "name": "New display name for the connection.",
    },
)


@connections.command("rename", cls=JsonHelpCommand)
@click.argument("connection_id_arg", required=False)
@click.option("--connection-id", default=None, help="The connection ID to rename.")
@click.option("--name", required=True, help="New display name for the connection.")
@click.pass_context
def connections_rename(
    ctx: click.Context,
    connection_id_arg: str | None,
    connection_id: str | None,
    name: str,
) -> None:
    """Rename a connection."""
    connection_id = resolve_entity_id(
        connection_id_arg,
        connection_id,
        option_name="--connection-id",
    )
    api_url, client_id, client_secret, _ = get_auth_context(ctx)
    result = api_util.patch_connection(
        connection_id=connection_id,
        name=name,
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
    )
    json_output(connection_to_dict(result))


register_schema(
    "connections_update",
    description="Update connection settings by ID.",
    required_params={
        "workspace_id": "The workspace ID.",
        "connection_id": "The connection ID to update, as an argument or --connection-id.",
    },
    optional_params={
        "prefix": "Optional table prefix for destination.",
        "selected_stream_name": "Stream name to sync. Repeat for multiple streams.",
        "status": "Connection status: active, inactive, or deprecated.",
    },
)


@connections.command("update", cls=JsonHelpCommand)
@click.argument("connection_id_arg", required=False)
@click.option("--connection-id", default=None, help="The connection ID to update.")
@click.option("--prefix", default=None, help="Optional table prefix for destination.")
@click.option("--selected-stream-name", multiple=True, help="Stream name to sync.")
@click.option(
    "--status",
    type=click.Choice(["active", "inactive", "deprecated"], case_sensitive=False),
    default=None,
    help="Connection status.",
)
@click.pass_context
def connections_update(
    ctx: click.Context,
    connection_id_arg: str | None,
    connection_id: str | None,
    prefix: str | None,
    selected_stream_name: tuple[str, ...],
    status: str | None,
) -> None:
    """Update a connection."""
    connection_id = resolve_entity_id(
        connection_id_arg,
        connection_id,
        option_name="--connection-id",
    )
    if prefix is None and not selected_stream_name and status is None:
        error_json(
            "Provide at least one update option.",
            type="MissingParameter",
        )
    configurations = (
        api_util.build_stream_configurations(list(selected_stream_name))
        if selected_stream_name
        else None
    )
    api_url, client_id, client_secret, _ = get_auth_context(ctx)
    result = api_util.patch_connection(
        connection_id=connection_id,
        configurations=configurations,
        prefix=prefix,
        status=status,
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
    )
    json_output(connection_to_dict(result))


register_schema(
    "connections_delete",
    description="Delete a connection by ID.",
    required_params={
        "workspace_id": "The workspace ID.",
        "connection_id": "The connection ID to delete, as an argument or --connection-id.",
    },
    optional_params={"force": "Skip delete safety checks (default: false)."},
)


@connections.command("delete", cls=JsonHelpCommand)
@click.argument("connection_id_arg", required=False)
@click.option("--connection-id", default=None, help="The connection ID to delete.")
@click.option("--force", is_flag=True, default=False, help="Skip delete safety checks.")
@click.pass_context
def connections_delete(
    ctx: click.Context,
    connection_id_arg: str | None,
    connection_id: str | None,
    force: bool,  # noqa: FBT001
) -> None:
    """Delete a connection."""
    connection_id = resolve_entity_id(
        connection_id_arg,
        connection_id,
        option_name="--connection-id",
    )
    api_url, client_id, client_secret, workspace_id = get_auth_context(ctx)
    api_util.delete_connection(
        connection_id,
        workspace_id=workspace_id,
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
        safe_mode=not force,
    )
    json_output({"deleted": True, "connection_id": connection_id})


register_schema(
    "connections_sync",
    description="Trigger a sync job for a connection.",
    required_params={
        "workspace_id": "The workspace ID.",
        "connection_id": "The connection ID to sync, as an argument or --connection-id.",
    },
    optional_params={
        "wait": "Wait for the triggered job to complete.",
        "wait_timeout": "Maximum seconds to wait for job completion.",
    },
)


@connections.command("sync", cls=JsonHelpCommand)
@click.argument("connection_id_arg", required=False)
@click.option("--connection-id", default=None, help="The connection ID to sync.")
@click.option("--wait/--no-wait", default=False, help="Wait for the triggered job to complete.")
@click.option(
    "--wait-timeout",
    default=api_util.JOB_WAIT_TIMEOUT_SECS_DEFAULT,
    type=int,
    help="Maximum seconds to wait for job completion.",
)
@click.pass_context
def connections_sync(
    ctx: click.Context,
    connection_id_arg: str | None,
    connection_id: str | None,
    wait: bool,  # noqa: FBT001
    wait_timeout: int,
) -> None:
    """Trigger a sync for a connection."""
    connection_id = resolve_entity_id(
        connection_id_arg,
        connection_id,
        option_name="--connection-id",
    )
    api_url, client_id, client_secret, workspace_id = get_auth_context(ctx)
    result = api_util.run_connection(
        workspace_id,
        connection_id,
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
    )
    if wait:
        result = api_util.wait_for_job(
            job_id=result.job_id,
            api_root=api_url,
            client_id=client_id,
            client_secret=client_secret,
            bearer_token=None,
            timeout_secs=wait_timeout,
        )
    json_output(job_to_dict(result))


__all__ = ["connections"]
