# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud connections` commands.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli_docs.py`.

.. include:: ../../../docs/generated/cli/cloud/connections.md
   :start-line: 2
"""

from __future__ import annotations

from typing import Annotated

from cyclopts import Parameter

from airbyte.cli._base import _create_app
from airbyte.cli._input import (
    ApiUrlArg,
    ClientIdArg,
    ClientSecretArg,
    ConnectionIdArg,
    PositionalIdArg,
    WorkspaceIdArg,
    parse_csv,
    resolve_entity_id,
    with_json_input,
)
from airbyte.cli._output import json_output
from airbyte.cli.cloud._cli import cloud_app
from airbyte.cloud.workspaces import CloudWorkspace
from airbyte.exceptions import PyAirbyteInputError


connections_app = _create_app(name="connections", help_text="Manage Airbyte Cloud connections.")
schedule_app = _create_app(name="schedule", help_text="Manage connection schedules.")
cloud_app.command(connections_app)
connections_app.command(schedule_app)


@connections_app.command(name="list")
def list_(
    *,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """List connections in the workspace."""
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    json_output([connection.get_info() for connection in workspace.list_connections()])


@connections_app.command
def get(
    *connection_id_args: PositionalIdArg,
    connection_id: ConnectionIdArg = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Get details of a specific connection."""
    resolved_connection_id = resolve_entity_id(
        connection_id_args,
        connection_id,
        option_name="--connection-id",
    )
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    json_output(workspace.get_connection(resolved_connection_id).get_info())


@connections_app.command
@with_json_input(comma_list_fields={"selected_streams"})
def create(  # noqa: PLR0913
    *,
    name: Annotated[str, Parameter(help="Display name for the connection.")],
    source_id: Annotated[str, Parameter(help="The source ID.")],
    destination_id: Annotated[str, Parameter(help="The destination ID.")],
    selected_streams: Annotated[
        str | None, Parameter(help="Comma-separated stream names to sync.")
    ] = None,
    prefix: Annotated[str, Parameter(help="Optional table prefix for destination.")] = "",
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Create a new connection."""
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    result = workspace.deploy_connection(
        connection_name=name,
        source=workspace.get_source(source_id),
        destination=workspace.get_destination(destination_id),
        table_prefix=prefix,
        selected_streams=parse_csv(selected_streams),
    )
    json_output(result.get_info())


@connections_app.command
def rename(
    *connection_id_args: PositionalIdArg,
    name: Annotated[str, Parameter(help="New display name for the connection.")],
    connection_id: ConnectionIdArg = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Rename a connection."""
    resolved_connection_id = resolve_entity_id(
        connection_id_args,
        connection_id,
        option_name="--connection-id",
    )
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    json_output(workspace.get_connection(resolved_connection_id).rename(name).get_info())


@connections_app.command
def update(
    *connection_id_args: PositionalIdArg,
    connection_id: ConnectionIdArg = None,
    prefix: Annotated[str | None, Parameter(help="Optional table prefix for destination.")] = None,
    selected_streams: Annotated[
        str | None, Parameter(help="Comma-separated stream names to sync.")
    ] = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Update a connection."""
    resolved_connection_id = resolve_entity_id(
        connection_id_args,
        connection_id,
        option_name="--connection-id",
    )
    if prefix is None and selected_streams is None:
        raise PyAirbyteInputError(message="At least one update option is required.")
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    connection = workspace.get_connection(resolved_connection_id)
    if prefix is not None:
        connection.set_table_prefix(prefix)
    if selected_streams is not None:
        connection.set_selected_streams(parse_csv(selected_streams))
    json_output(connection.get_info())


@connections_app.command
def enable(
    *connection_id_args: PositionalIdArg,
    connection_id: ConnectionIdArg = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Enable a connection."""
    resolved_connection_id = resolve_entity_id(
        connection_id_args,
        connection_id,
        option_name="--connection-id",
    )
    connection = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    ).get_connection(resolved_connection_id)
    connection.set_enabled(enabled=True)
    json_output(connection.get_info())


@connections_app.command
def disable(
    *connection_id_args: PositionalIdArg,
    connection_id: ConnectionIdArg = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Disable a connection."""
    resolved_connection_id = resolve_entity_id(
        connection_id_args,
        connection_id,
        option_name="--connection-id",
    )
    connection = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    ).get_connection(resolved_connection_id)
    connection.set_enabled(enabled=False)
    json_output(connection.get_info())


@schedule_app.command(name="set")
def set_(
    *connection_id_args: PositionalIdArg,
    cron_expression: Annotated[str, Parameter(help="Cron expression for automatic syncs.")],
    connection_id: ConnectionIdArg = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Set a cron schedule for a connection."""
    resolved_connection_id = resolve_entity_id(
        connection_id_args,
        connection_id,
        option_name="--connection-id",
    )
    connection = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    ).get_connection(resolved_connection_id)
    connection.set_schedule(cron_expression)
    json_output(connection.get_info())


@schedule_app.command
def manual(
    *connection_id_args: PositionalIdArg,
    connection_id: ConnectionIdArg = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Set a connection to manual scheduling."""
    resolved_connection_id = resolve_entity_id(
        connection_id_args,
        connection_id,
        option_name="--connection-id",
    )
    connection = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    ).get_connection(resolved_connection_id)
    connection.set_manual_schedule()
    json_output(connection.get_info())


@connections_app.command
def delete(
    *connection_id_args: PositionalIdArg,
    connection_id: ConnectionIdArg = None,
    force: Annotated[bool, Parameter(help="Skip delete safety checks.")] = False,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Delete a connection."""
    resolved_connection_id = resolve_entity_id(
        connection_id_args,
        connection_id,
        option_name="--connection-id",
    )
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    workspace.permanently_delete_connection(
        connection=workspace.get_connection(resolved_connection_id),
        safe_mode=not force,
    )
    json_output({"deleted": True, "connection_id": resolved_connection_id})


@connections_app.command
def sync(
    *connection_id_args: PositionalIdArg,
    connection_id: ConnectionIdArg = None,
    wait: Annotated[
        bool, Parameter(negative="--no-wait", help="Wait for the triggered job to complete.")
    ] = False,
    wait_timeout: Annotated[
        int, Parameter(help="Maximum seconds to wait for job completion.")
    ] = 300,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Trigger a sync for a connection."""
    resolved_connection_id = resolve_entity_id(
        connection_id_args,
        connection_id,
        option_name="--connection-id",
    )
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    result = workspace.get_connection(resolved_connection_id).run_sync(
        wait=wait,
        wait_timeout=wait_timeout,
    )
    if wait:
        json_output(result.get_info())
    else:
        json_output({"job_id": result.job_id, "job_url": result.job_url})


__all__ = ["connections_app", "schedule_app"]
