# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud destinations` commands.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli_docs.py`.

.. include:: ../../../docs/generated/cli/cloud/destinations.md
   :start-line: 2
"""

from __future__ import annotations

from pathlib import Path  # noqa: TC003
from typing import Annotated

from cyclopts import Parameter

from airbyte.cli._base import _create_app
from airbyte.cli._input import (
    ApiUrlArg,
    ClientIdArg,
    ClientSecretArg,
    DestinationIdArg,
    PositionalIdArg,
    WorkspaceIdArg,
    parse_config_options,
    resolve_entity_id,
)
from airbyte.cli._output import json_output
from airbyte.cli.cloud._cli import cloud_app
from airbyte.cloud.workspaces import CloudWorkspace


destinations_app = _create_app(name="destinations", help_text="Manage Airbyte Cloud destinations.")
cloud_app.command(destinations_app)


@destinations_app.command(name="list")
def list_(
    *,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """List destinations in the workspace."""
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    json_output([destination.get_info() for destination in workspace.list_destinations()])


@destinations_app.command
def describe(
    *destination_id_args: PositionalIdArg,
    destination_id: DestinationIdArg = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Describe a specific destination."""
    resolved_destination_id = resolve_entity_id(
        destination_id_args,
        destination_id,
        option_name="--destination-id",
    )
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    json_output(workspace.get_destination(resolved_destination_id).get_info())


@destinations_app.command
def create(
    *,
    name: Annotated[str, Parameter(help="Display name for the destination.")],
    destination_type: Annotated[str, Parameter(help="The destination connector type.")],
    config_file: Annotated[
        Path | None, Parameter(help="JSON or YAML connector config file.")
    ] = None,
    config_json: Annotated[
        str | None, Parameter(help="Inline JSON connector config object.")
    ] = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Create a new destination in the workspace."""
    config = parse_config_options(config_json=config_json, config_file=config_file)
    config["destinationType"] = destination_type
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    json_output(workspace.deploy_destination(name=name, destination=config).get_info())


@destinations_app.command
def rename(
    *destination_id_args: PositionalIdArg,
    name: Annotated[str, Parameter(help="New display name for the destination.")],
    destination_id: DestinationIdArg = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Rename a destination."""
    resolved_destination_id = resolve_entity_id(
        destination_id_args,
        destination_id,
        option_name="--destination-id",
    )
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    json_output(workspace.get_destination(resolved_destination_id).rename(name).get_info())


@destinations_app.command
def update(
    *destination_id_args: PositionalIdArg,
    destination_id: DestinationIdArg = None,
    config_file: Annotated[
        Path | None, Parameter(help="JSON or YAML connector config file.")
    ] = None,
    config_json: Annotated[
        str | None, Parameter(help="Inline JSON connector config object.")
    ] = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Update a destination configuration."""
    resolved_destination_id = resolve_entity_id(
        destination_id_args,
        destination_id,
        option_name="--destination-id",
    )
    config = parse_config_options(config_json=config_json, config_file=config_file)
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    json_output(workspace.get_destination(resolved_destination_id).update_config(config).get_info())


@destinations_app.command
def delete(
    *destination_id_args: PositionalIdArg,
    destination_id: DestinationIdArg = None,
    force: Annotated[bool, Parameter(help="Skip delete safety checks.")] = False,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    public_api_root: ApiUrlArg = None,
) -> None:
    """Delete a destination."""
    resolved_destination_id = resolve_entity_id(
        destination_id_args,
        destination_id,
        option_name="--destination-id",
    )
    workspace = CloudWorkspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_root=public_api_root,
    )
    workspace.permanently_delete_destination(
        destination=workspace.get_destination(resolved_destination_id),
        safe_mode=not force,
    )
    json_output({"deleted": True, "destination_id": resolved_destination_id})


__all__ = ["destinations_app"]
