# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud destinations` commands.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud/destinations.md
   :start-line: 2
"""

from __future__ import annotations

from pathlib import Path  # noqa: TC003
from typing import Annotated

from cyclopts import Parameter

from airbyte.cli._base import _create_app
from airbyte.cli._cli_auth import (
    resolve_api_url,
    resolve_client_id,
    resolve_client_secret,
    resolve_workspace_id,
)
from airbyte.cli._input import parse_config_options, resolve_entity_id
from airbyte.cli._output import json_output
from airbyte.cli.cloud._cli import cloud_app
from airbyte.cloud import CloudWorkspace
from airbyte.secrets.base import SecretString


destinations_app = _create_app(name="destinations", help_text="Manage Airbyte Cloud destinations.")
cloud_app.command(destinations_app)


WorkspaceId = Annotated[
    str | None,
    Parameter(
        name="--workspace-id",
        env_var=["AIRBYTE_WORKSPACE_ID", "AIRBYTE_CLOUD_WORKSPACE_ID"],
        help="The workspace ID.",
    ),
]
ClientId = Annotated[
    str | None,
    Parameter(env_var=["AIRBYTE_CLIENT_ID", "AIRBYTE_CLOUD_CLIENT_ID"], help="Airbyte client ID."),
]
ClientSecret = Annotated[
    str | None,
    Parameter(
        env_var=["AIRBYTE_CLIENT_SECRET", "AIRBYTE_CLOUD_CLIENT_SECRET"],
        help="Airbyte client secret.",
    ),
]
ApiUrl = Annotated[str | None, Parameter(help="Airbyte API URL override.")]
DestinationId = Annotated[
    str | None, Parameter(name="--destination-id", help="The destination ID.")
]


@destinations_app.command(name="list")
def list_(
    *,
    workspace_id: WorkspaceId = None,
    client_id: ClientId = None,
    client_secret: ClientSecret = None,
    api_url: ApiUrl = None,
) -> None:
    """List destinations in the workspace."""
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    json_output([destination.get_info() for destination in workspace.list_destinations()])


@destinations_app.command
def get(
    *destination_id_args: Annotated[str, Parameter(show=False, consume_multiple=True)],
    destination_id: DestinationId = None,
    workspace_id: WorkspaceId = None,
    client_id: ClientId = None,
    client_secret: ClientSecret = None,
    api_url: ApiUrl = None,
) -> None:
    """Get details of a specific destination."""
    resolved_destination_id = resolve_entity_id(
        destination_id_args,
        destination_id,
        option_name="--destination-id",
    )
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    json_output(workspace.get_destination(resolved_destination_id).get_info())


@destinations_app.command
def create(
    *,
    name: Annotated[str, Parameter(help="Display name for the destination.")],
    destination_type: Annotated[str, Parameter(help="The destination connector type.")],
    config_file: Annotated[
        Path | None, Parameter(help="JSON or YAML connector config file.")
    ] = None,
    config_json: Annotated[
        str | None, Parameter(help="Inline JSON connector config object.")
    ] = None,
    workspace_id: WorkspaceId = None,
    client_id: ClientId = None,
    client_secret: ClientSecret = None,
    api_url: ApiUrl = None,
) -> None:
    """Create a new destination in the workspace."""
    config = parse_config_options(config_json=config_json, config_file=config_file)
    config["destinationType"] = destination_type
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    json_output(workspace.deploy_destination(name=name, destination=config).get_info())


@destinations_app.command
def rename(
    *destination_id_args: Annotated[str, Parameter(show=False, consume_multiple=True)],
    name: Annotated[str, Parameter(help="New display name for the destination.")],
    destination_id: DestinationId = None,
    workspace_id: WorkspaceId = None,
    client_id: ClientId = None,
    client_secret: ClientSecret = None,
    api_url: ApiUrl = None,
) -> None:
    """Rename a destination."""
    resolved_destination_id = resolve_entity_id(
        destination_id_args,
        destination_id,
        option_name="--destination-id",
    )
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    json_output(workspace.get_destination(resolved_destination_id).rename(name).get_info())


@destinations_app.command
def update(
    *destination_id_args: Annotated[str, Parameter(show=False, consume_multiple=True)],
    destination_id: DestinationId = None,
    config_file: Annotated[
        Path | None, Parameter(help="JSON or YAML connector config file.")
    ] = None,
    config_json: Annotated[
        str | None, Parameter(help="Inline JSON connector config object.")
    ] = None,
    workspace_id: WorkspaceId = None,
    client_id: ClientId = None,
    client_secret: ClientSecret = None,
    api_url: ApiUrl = None,
) -> None:
    """Update a destination configuration."""
    resolved_destination_id = resolve_entity_id(
        destination_id_args,
        destination_id,
        option_name="--destination-id",
    )
    config = parse_config_options(config_json=config_json, config_file=config_file)
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    json_output(workspace.get_destination(resolved_destination_id).update_config(config).get_info())


@destinations_app.command
def delete(
    *destination_id_args: Annotated[str, Parameter(show=False, consume_multiple=True)],
    destination_id: DestinationId = None,
    force: Annotated[bool, Parameter(help="Skip delete safety checks.")] = False,
    workspace_id: WorkspaceId = None,
    client_id: ClientId = None,
    client_secret: ClientSecret = None,
    api_url: ApiUrl = None,
) -> None:
    """Delete a destination."""
    resolved_destination_id = resolve_entity_id(
        destination_id_args,
        destination_id,
        option_name="--destination-id",
    )
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    workspace.permanently_delete_destination(
        destination=workspace.get_destination(resolved_destination_id),
        safe_mode=not force,
    )
    json_output({"deleted": True, "destination_id": resolved_destination_id})


__all__ = ["destinations_app"]
