# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud jobs` commands.

The commands below are regenerated by `poe docs-generate` from the Click command
tree; see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud/jobs.md
   :start-line: 2
"""

from __future__ import annotations

import click

from airbyte._util import api_util
from airbyte.cli.cloud._api_helpers import get_auth_context, get_auth_no_workspace, job_to_dict
from airbyte.cli.cloud._json_helpers import (
    JsonHelpCommand,
    JsonHelpGroup,
    error_json,
    json_output,
    register_schema,
    resolve_entity_id,
)


@click.group(cls=JsonHelpGroup)
@click.pass_context
def jobs(ctx: click.Context) -> None:
    """View Airbyte sync jobs."""
    pass


register_schema(
    "jobs_list",
    description="List recent sync jobs for a connection.",
    required_params={
        "workspace_id": "The workspace ID.",
        "connection_id": "The connection ID.",
    },
    optional_params={"limit": "Maximum number of jobs to return (default: 20)."},
)


@jobs.command("list", cls=JsonHelpCommand)
@click.option("--connection-id", default=None, help="The connection ID to list jobs for.")
@click.option("--limit", default=20, help="Maximum number of jobs to return.")
@click.pass_context
def jobs_list(ctx: click.Context, connection_id: str | None, limit: int) -> None:
    """List recent jobs for a connection."""
    if not connection_id:
        error_json("--connection-id is required.", type="MissingParameter")
    assert connection_id is not None
    api_url, client_id, client_secret, workspace_id = get_auth_context(ctx)
    results = api_util.get_job_logs(
        workspace_id,
        connection_id,
        limit,
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
    )
    json_output([job_to_dict(j) for j in results])


register_schema(
    "jobs_get",
    description="Get details of a specific job by ID.",
    required_params={"job_id": "The job ID to retrieve, as an argument or --job-id."},
)


@jobs.command("get", cls=JsonHelpCommand)
@click.argument("job_id_arg", required=False, type=int)
@click.option("--job-id", default=None, type=int, help="The job ID to retrieve.")
@click.pass_context
def jobs_get(ctx: click.Context, job_id_arg: int | None, job_id: int | None) -> None:
    """Get details of a specific job."""
    job_id = int(
        resolve_entity_id(
            str(job_id_arg) if job_id_arg is not None else None,
            str(job_id) if job_id is not None else None,
            option_name="--job-id",
        )
    )
    api_url, client_id, client_secret = get_auth_no_workspace(ctx)
    result = api_util.get_job_info(
        job_id=job_id,
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
    )
    json_output(job_to_dict(result))


register_schema(
    "jobs_wait",
    description="Wait for a job to reach a terminal status.",
    required_params={"job_id": "The job ID to wait for, as an argument or --job-id."},
    optional_params={"wait_timeout": "Maximum seconds to wait for job completion."},
)


@jobs.command("wait", cls=JsonHelpCommand)
@click.argument("job_id_arg", required=False, type=int)
@click.option("--job-id", default=None, type=int, help="The job ID to wait for.")
@click.option(
    "--wait-timeout",
    default=api_util.JOB_WAIT_TIMEOUT_SECS_DEFAULT,
    type=int,
    help="Maximum seconds to wait for job completion.",
)
@click.pass_context
def jobs_wait(
    ctx: click.Context, job_id_arg: int | None, job_id: int | None, wait_timeout: int
) -> None:
    """Wait for a job to complete."""
    job_id = int(
        resolve_entity_id(
            str(job_id_arg) if job_id_arg is not None else None,
            str(job_id) if job_id is not None else None,
            option_name="--job-id",
        )
    )
    api_url, client_id, client_secret = get_auth_no_workspace(ctx)
    result = api_util.wait_for_job(
        job_id=job_id,
        api_root=api_url,
        client_id=client_id,
        client_secret=client_secret,
        bearer_token=None,
        timeout_secs=wait_timeout,
    )
    json_output(job_to_dict(result))


__all__ = ["jobs"]
