# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud jobs` commands.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud/jobs.md
   :start-line: 2
"""

from __future__ import annotations

from typing import Annotated

from cyclopts import Parameter

from airbyte.cli._base import _create_app
from airbyte.cli._cli_auth import (
    resolve_api_url,
    resolve_client_id,
    resolve_client_secret,
    resolve_workspace_id,
)
from airbyte.cli._input import (
    ApiUrlArg,
    ClientIdArg,
    ClientSecretArg,
    JobIdArg,
    PositionalIdArg,
    WorkspaceIdArg,
    resolve_entity_id,
)
from airbyte.cli._output import json_output
from airbyte.cli.cloud._cli import cloud_app
from airbyte.cloud import CloudWorkspace
from airbyte.exceptions import PyAirbyteInputError
from airbyte.secrets.base import SecretString


jobs_app = _create_app(name="jobs", help_text="View Airbyte sync jobs.")
cloud_app.command(jobs_app)


def _resolve_job_id(args: tuple[str, ...], job_id: int | None) -> int:
    return int(
        resolve_entity_id(
            args,
            str(job_id) if job_id is not None else None,
            option_name="--job-id",
        )
    )


@jobs_app.command(name="list")
def list_(
    *,
    connection_id: Annotated[str, Parameter(help="The connection ID to list jobs for.")],
    limit: Annotated[int, Parameter(help="Maximum number of jobs to return.")] = 20,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    api_url: ApiUrlArg = None,
) -> None:
    """List recent jobs for a connection."""
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    results = workspace.get_connection(connection_id).get_previous_sync_logs(limit=limit)
    json_output([job.get_info() for job in results])


@jobs_app.command
def get(
    *job_id_args: PositionalIdArg,
    job_id: JobIdArg = None,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    api_url: ApiUrlArg = None,
) -> None:
    """Get details of a specific job."""
    resolved_job_id = _resolve_job_id(job_id_args, job_id)
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    json_output(workspace.get_job_info(resolved_job_id))


@jobs_app.command
def wait(
    *job_id_args: PositionalIdArg,
    job_id: JobIdArg = None,
    wait_timeout: Annotated[
        int, Parameter(help="Maximum seconds to wait for job completion.")
    ] = 300,
    workspace_id: WorkspaceIdArg = None,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    api_url: ApiUrlArg = None,
) -> None:
    """Wait for a job to complete."""
    resolved_job_id = _resolve_job_id(job_id_args, job_id)
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    job = workspace.get_job_info(resolved_job_id)
    result = workspace.get_connection(job.connection_id).get_sync_result(resolved_job_id)
    if result is None:
        raise PyAirbyteInputError(message="Sync result is not available.")
    result.wait_for_completion(wait_timeout=wait_timeout)
    json_output(result.get_info())


__all__ = ["jobs_app"]
