# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud jobs` commands.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud/jobs.md
   :start-line: 2
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Annotated

from cyclopts import Parameter


if TYPE_CHECKING:
    from airbyte.cloud import CloudWorkspace

from airbyte.cli._base import _create_app
from airbyte.cli._output import json_output
from airbyte.cli.cloud._api_helpers import get_cloud_workspace, job_to_dict, resolve_entity_id
from airbyte.cli.cloud._cli import cloud_app
from airbyte.exceptions import PyAirbyteInputError


jobs_app = _create_app(name="jobs", help_text="View Airbyte sync jobs.")
cloud_app.command(jobs_app)


WorkspaceId = Annotated[
    str | None,
    Parameter(
        name="--workspace-id",
        env_var=["AIRBYTE_WORKSPACE_ID", "AIRBYTE_CLOUD_WORKSPACE_ID"],
        help="The workspace ID.",
    ),
]
ClientId = Annotated[
    str | None,
    Parameter(env_var=["AIRBYTE_CLIENT_ID", "AIRBYTE_CLOUD_CLIENT_ID"], help="Airbyte client ID."),
]
ClientSecret = Annotated[
    str | None,
    Parameter(
        env_var=["AIRBYTE_CLIENT_SECRET", "AIRBYTE_CLOUD_CLIENT_SECRET"],
        help="Airbyte client secret.",
    ),
]
ApiUrl = Annotated[str | None, Parameter(help="Airbyte API URL override.")]
JobId = Annotated[int | None, Parameter(name="--job-id", help="The job ID.")]


def _workspace(
    workspace_id: str | None, client_id: str | None, client_secret: str | None, api_url: str | None
) -> CloudWorkspace:
    return get_cloud_workspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_url=api_url,
    )


def _resolve_job_id(args: tuple[str, ...], job_id: int | None) -> int:
    return int(
        resolve_entity_id(
            args,
            str(job_id) if job_id is not None else None,
            option_name="--job-id",
        )
    )


@jobs_app.command(name="list")
def list_(
    *,
    connection_id: Annotated[str, Parameter(help="The connection ID to list jobs for.")],
    limit: Annotated[int, Parameter(help="Maximum number of jobs to return.")] = 20,
    workspace_id: WorkspaceId = None,
    client_id: ClientId = None,
    client_secret: ClientSecret = None,
    api_url: ApiUrl = None,
) -> None:
    """List recent jobs for a connection."""
    workspace = _workspace(workspace_id, client_id, client_secret, api_url)
    results = workspace.get_connection(connection_id).get_previous_sync_logs(limit=limit)
    json_output([job_to_dict(job) for job in results])


@jobs_app.command
def get(
    *job_id_args: Annotated[str, Parameter(show=False, consume_multiple=True)],
    job_id: JobId = None,
    workspace_id: WorkspaceId = None,
    client_id: ClientId = None,
    client_secret: ClientSecret = None,
    api_url: ApiUrl = None,
) -> None:
    """Get details of a specific job."""
    resolved_job_id = _resolve_job_id(job_id_args, job_id)
    workspace = _workspace(workspace_id, client_id, client_secret, api_url)
    json_output(job_to_dict(workspace.get_job_info(resolved_job_id)))


@jobs_app.command
def wait(
    *job_id_args: Annotated[str, Parameter(show=False, consume_multiple=True)],
    job_id: JobId = None,
    wait_timeout: Annotated[
        int, Parameter(help="Maximum seconds to wait for job completion.")
    ] = 300,
    workspace_id: WorkspaceId = None,
    client_id: ClientId = None,
    client_secret: ClientSecret = None,
    api_url: ApiUrl = None,
) -> None:
    """Wait for a job to complete."""
    resolved_job_id = _resolve_job_id(job_id_args, job_id)
    workspace = _workspace(workspace_id, client_id, client_secret, api_url)
    job = workspace.get_job_info(resolved_job_id)
    result = workspace.get_connection(job.connection_id).get_sync_result(resolved_job_id)
    if result is None:
        raise PyAirbyteInputError(message="Sync result is not available.")
    result.wait_for_completion(wait_timeout=wait_timeout)
    json_output(job_to_dict(result))


__all__ = ["jobs_app"]
