# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud sources` commands.

The commands below are regenerated by `poe docs-generate` from the Click command
tree; see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud/sources.md
   :start-line: 2
"""

from __future__ import annotations

import click

from airbyte.cli.cloud._api_helpers import get_cloud_workspace, source_to_dict
from airbyte.cli.cloud._json_helpers import (
    JsonHelpCommand,
    JsonHelpGroup,
    error_json,
    json_output,
    parse_config_options,
    register_schema,
    resolve_entity_id,
)


@click.group(cls=JsonHelpGroup)
@click.pass_context
def sources(ctx: click.Context) -> None:
    """Manage Airbyte sources."""
    pass


register_schema(
    "sources_list",
    description="List all sources in the workspace.",
    required_params={"workspace_id": "The workspace ID."},
)


@sources.command("list", cls=JsonHelpCommand)
@click.pass_context
def sources_list(ctx: click.Context) -> None:
    """List sources in the workspace."""
    workspace = get_cloud_workspace(ctx)
    results = workspace.list_sources()
    json_output([source_to_dict(s) for s in results])


register_schema(
    "sources_get",
    description="Get details of a specific source.",
    required_params={"source_id": "The source ID to retrieve, as an argument or --source-id."},
)


@sources.command("get", cls=JsonHelpCommand)
@click.argument("source_id_arg", required=False)
@click.option("--source-id", default=None, help="The source ID to retrieve.")
@click.pass_context
def sources_get(ctx: click.Context, source_id_arg: str | None, source_id: str | None) -> None:
    """Get details of a specific source."""
    source_id = resolve_entity_id(source_id_arg, source_id, option_name="--source-id")
    workspace = get_cloud_workspace(ctx)
    result = workspace.get_source(source_id)
    json_output(source_to_dict(result))


register_schema(
    "sources_create",
    description="Create a new source in the workspace.",
    required_params={
        "workspace_id": "The workspace ID.",
        "name": "Display name for the source.",
        "source_type": "The source connector type (e.g. 'postgres').",
    },
    optional_params={
        "config_file": "JSON or YAML file containing connector-specific configuration.",
        "config_json": "Inline JSON object containing connector-specific configuration.",
    },
)


@sources.command("create", cls=JsonHelpCommand)
@click.option("--name", required=True, help="Display name for the source.")
@click.option("--source-type", required=True, help="The source connector type.")
@click.option("--config-file", default=None, help="JSON or YAML connector config file.")
@click.option("--config-json", default=None, help="Inline JSON connector config object.")
@click.pass_context
def sources_create(
    ctx: click.Context,
    name: str,
    source_type: str,
    config_file: str | None,
    config_json: str | None,
) -> None:
    """Create a new source in the workspace."""
    config = parse_config_options(
        config_json,
        config_file,
        config_type_key="sourceType",
        config_type_value=source_type,
    )
    workspace = get_cloud_workspace(ctx)
    result = workspace.deploy_source(
        name=name,
        config=config,
    )
    json_output(source_to_dict(result))


register_schema(
    "sources_rename",
    description="Rename a source by ID.",
    required_params={
        "source_id": "The source ID to rename, as an argument or --source-id.",
        "name": "New display name for the source.",
    },
)


@sources.command("rename", cls=JsonHelpCommand)
@click.argument("source_id_arg", required=False)
@click.option("--source-id", default=None, help="The source ID to rename.")
@click.option("--name", required=True, help="New display name for the source.")
@click.pass_context
def sources_rename(
    ctx: click.Context,
    source_id_arg: str | None,
    source_id: str | None,
    name: str,
) -> None:
    """Rename a source."""
    source_id = resolve_entity_id(source_id_arg, source_id, option_name="--source-id")
    workspace = get_cloud_workspace(ctx)
    result = workspace.get_source(source_id).rename(name)
    json_output(source_to_dict(result))


register_schema(
    "sources_update",
    description="Update source connector configuration by ID.",
    required_params={
        "source_id": "The source ID to update, as an argument or --source-id.",
    },
    optional_params={
        "config_file": "JSON or YAML file containing connector-specific configuration.",
        "config_json": "Inline JSON object containing connector-specific configuration.",
    },
)


@sources.command("update", cls=JsonHelpCommand)
@click.argument("source_id_arg", required=False)
@click.option("--source-id", default=None, help="The source ID to update.")
@click.option("--config-file", default=None, help="JSON or YAML connector config file.")
@click.option("--config-json", default=None, help="Inline JSON connector config object.")
@click.pass_context
def sources_update(
    ctx: click.Context,
    source_id_arg: str | None,
    source_id: str | None,
    config_file: str | None,
    config_json: str | None,
) -> None:
    """Update a source configuration."""
    source_id = resolve_entity_id(source_id_arg, source_id, option_name="--source-id")
    if not config_file and not config_json:
        error_json("Provide --config-file or --config-json.", type="MissingParameter")
    config = parse_config_options(config_json, config_file)
    workspace = get_cloud_workspace(ctx)
    result = workspace.get_source(source_id).update_config(config)
    json_output(source_to_dict(result))


register_schema(
    "sources_delete",
    description="Delete a source by ID.",
    required_params={
        "workspace_id": "The workspace ID.",
        "source_id": "The source ID to delete, as an argument or --source-id.",
    },
    optional_params={"force": "Skip delete safety checks (default: false)."},
)


@sources.command("delete", cls=JsonHelpCommand)
@click.argument("source_id_arg", required=False)
@click.option("--source-id", default=None, help="The source ID to delete.")
@click.option("--force", is_flag=True, default=False, help="Skip delete safety checks.")
@click.pass_context
def sources_delete(
    ctx: click.Context,
    source_id_arg: str | None,
    source_id: str | None,
    force: bool,  # noqa: FBT001
) -> None:
    """Delete a source."""
    source_id = resolve_entity_id(source_id_arg, source_id, option_name="--source-id")
    workspace = get_cloud_workspace(ctx)
    workspace.permanently_delete_source(
        source=workspace.get_source(source_id),
        safe_mode=not force,
    )
    json_output({"deleted": True, "source_id": source_id})


__all__ = ["sources"]
