# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud workspaces` commands.

The commands below are regenerated by `poe docs-generate` from the Click command
tree; see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud/workspaces.md
   :start-line: 2
"""

from __future__ import annotations

import click

from airbyte.cli._cli_auth import resolve_workspace_id
from airbyte.cli.cloud._api_helpers import get_cloud_workspace, workspace_to_dict
from airbyte.cli.cloud._json_helpers import (
    JsonHelpCommand,
    JsonHelpGroup,
    json_output,
    register_schema,
)


@click.group(cls=JsonHelpGroup)
@click.pass_context
def workspaces(ctx: click.Context) -> None:
    """Manage Airbyte workspaces."""
    pass


register_schema(
    "workspaces_list",
    description="List all workspaces accessible with the current credentials.",
    optional_params={"workspace_id": "Filter to a specific workspace ID."},
)


@workspaces.command("list", cls=JsonHelpCommand)
@click.pass_context
def workspaces_list(ctx: click.Context) -> None:
    """List workspaces accessible with the current credentials."""
    workspace = get_cloud_workspace(ctx)
    json_output([workspace_to_dict(workspace.get_info())])


register_schema(
    "workspaces_get",
    description="Get details of a specific workspace.",
    required_params={"workspace_id": "The workspace ID to retrieve."},
)


@workspaces.command("get", cls=JsonHelpCommand)
@click.option("--workspace-id", "cmd_workspace_id", default=None, help="Workspace ID to retrieve.")
@click.pass_context
def workspaces_get(ctx: click.Context, cmd_workspace_id: str | None) -> None:
    """Get details of a specific workspace."""
    workspace_id = resolve_workspace_id(cmd_workspace_id or ctx.obj["_raw_workspace_id"])
    workspace = get_cloud_workspace(ctx, workspace_id=workspace_id)
    json_output(workspace_to_dict(workspace.get_info()))


__all__ = ["workspaces"]
