# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud workspaces` commands.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud/workspaces.md
   :start-line: 2
"""

from __future__ import annotations

from typing import Annotated

from cyclopts import Parameter

from airbyte.cli._base import _create_app
from airbyte.cli._output import json_output
from airbyte.cli.cloud._api_helpers import get_cloud_workspace, workspace_to_dict
from airbyte.cli.cloud._cli import cloud_app


workspaces_app = _create_app(name="workspaces", help_text="Manage Airbyte Cloud workspaces.")
cloud_app.command(workspaces_app)


@workspaces_app.command(name="list")
def list_(
    *,
    client_id: Annotated[
        str | None,
        Parameter(
            env_var=["AIRBYTE_CLIENT_ID", "AIRBYTE_CLOUD_CLIENT_ID"], help="Airbyte client ID."
        ),
    ] = None,
    client_secret: Annotated[
        str | None,
        Parameter(
            env_var=["AIRBYTE_CLIENT_SECRET", "AIRBYTE_CLOUD_CLIENT_SECRET"],
            help="Airbyte client secret.",
        ),
    ] = None,
    api_url: Annotated[str | None, Parameter(help="Airbyte API URL override.")] = None,
) -> None:
    """List workspaces."""
    workspace = get_cloud_workspace(
        workspace_id="00000000-0000-0000-0000-000000000000",
        client_id=client_id,
        client_secret=client_secret,
        api_url=api_url,
    )
    workspaces = workspace.list_workspaces()  # pyrefly: ignore[missing-attribute]
    json_output([workspace_to_dict(ws) for ws in workspaces])


@workspaces_app.command
def get(
    workspace_id: Annotated[
        str | None,
        Parameter(
            name="--workspace-id",
            env_var=["AIRBYTE_WORKSPACE_ID", "AIRBYTE_CLOUD_WORKSPACE_ID"],
            help="The workspace ID.",
        ),
    ] = None,
    *,
    client_id: Annotated[
        str | None,
        Parameter(
            env_var=["AIRBYTE_CLIENT_ID", "AIRBYTE_CLOUD_CLIENT_ID"], help="Airbyte client ID."
        ),
    ] = None,
    client_secret: Annotated[
        str | None,
        Parameter(
            env_var=["AIRBYTE_CLIENT_SECRET", "AIRBYTE_CLOUD_CLIENT_SECRET"],
            help="Airbyte client secret.",
        ),
    ] = None,
    api_url: Annotated[str | None, Parameter(help="Airbyte API URL override.")] = None,
) -> None:
    """Get workspace details."""
    workspace = get_cloud_workspace(
        workspace_id=workspace_id,
        client_id=client_id,
        client_secret=client_secret,
        api_url=api_url,
    )
    json_output(workspace_to_dict(workspace.get_info()))


__all__ = ["workspaces_app"]
