# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte cloud workspaces` commands.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/cloud/workspaces.md
   :start-line: 2
"""

from __future__ import annotations

from airbyte.cli._base import _create_app
from airbyte.cli._cli_auth import (
    resolve_api_url,
    resolve_client_id,
    resolve_client_secret,
    resolve_workspace_id,
)
from airbyte.cli._input import (  # noqa: TC001
    ApiUrlArg,
    ClientIdArg,
    ClientSecretArg,
    WorkspaceIdArg,
)
from airbyte.cli._output import json_output
from airbyte.cli.cloud._cli import cloud_app
from airbyte.cloud import CloudWorkspace
from airbyte.secrets.base import SecretString


workspaces_app = _create_app(name="workspaces", help_text="Manage Airbyte Cloud workspaces.")
cloud_app.command(workspaces_app)


@workspaces_app.command(name="list")
def list_(
    *,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    api_url: ApiUrlArg = None,
) -> None:
    """List workspaces."""
    workspace = CloudWorkspace(
        workspace_id="00000000-0000-0000-0000-000000000000",
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    json_output(workspace.list_workspaces())


@workspaces_app.command
def get(
    workspace_id: WorkspaceIdArg = None,
    *,
    client_id: ClientIdArg = None,
    client_secret: ClientSecretArg = None,
    api_url: ApiUrlArg = None,
) -> None:
    """Get workspace details."""
    workspace = CloudWorkspace(
        workspace_id=resolve_workspace_id(workspace_id),
        api_root=resolve_api_url(api_url),
        client_id=SecretString(resolve_client_id(client_id)),
        client_secret=SecretString(resolve_client_secret(client_secret)),
    )
    json_output(workspace.get_info())


__all__ = ["workspaces_app"]
