# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte local` CLI reference.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli_docs.py`.

.. include:: ../../../docs/generated/cli/local-reference.md
   :start-line: 2
"""

from __future__ import annotations

from airbyte.cli.local import connectors, debug, sync
from airbyte.cli.local._cli import local_app


__all__ = [
    "connectors",
    "debug",
    "local_app",
    "sync",
]
