# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte local connectors` commands.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/local/connectors.md
   :start-line: 2
"""

from __future__ import annotations

from typing import Annotated

from cyclopts import Parameter

from airbyte.cli._base import _create_app
from airbyte.cli.local._cli import local_app
from airbyte.cli.pyab import benchmark as run_benchmark
from airbyte.cli.pyab import validate as run_validate


connectors_app = _create_app(
    name="connectors", help_text="Run local connector development commands."
)
local_app.command(connectors_app)


@connectors_app.command
def validate(
    *,
    connector: Annotated[str, Parameter(help="The connector name or path to a local executable.")],
    config: Annotated[
        str | None, Parameter(help="Connector configuration file or inline YAML.")
    ] = None,
    pip_url: Annotated[
        str | None, Parameter(help="Optional pip URL for Python connectors.")
    ] = None,
    use_python: Annotated[str | None, Parameter(help="Python interpreter specification.")] = None,
) -> None:
    """Validate a connector locally."""
    run_validate(connector=connector, config=config, pip_url=pip_url, use_python=use_python)


@connectors_app.command
def benchmark(
    *,
    source: Annotated[str | None, Parameter(help="The source connector to benchmark.")] = None,
    streams: Annotated[str, Parameter(help="Comma-separated stream names or `*`.")] = "*",
    num_records: Annotated[str, Parameter(help="Number of synthetic records to generate.")] = "5e5",
    destination: Annotated[
        str | None, Parameter(help="The destination connector to benchmark.")
    ] = None,
    config: Annotated[
        str | None, Parameter(help="Connector configuration file or inline YAML.")
    ] = None,
    use_python: Annotated[str | None, Parameter(help="Python interpreter specification.")] = None,
) -> None:
    """Run a local connector benchmark."""
    run_benchmark(
        source=source,
        streams=streams,
        num_records=num_records,
        destination=destination,
        config=config,
        use_python=use_python,
    )


__all__ = ["connectors_app"]
