# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte local connectors` commands.

The commands below are regenerated by `poe docs-generate` from the Click command
tree; see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/local/connectors.md
   :start-line: 2
"""

from __future__ import annotations

import click

from airbyte.cli.pyab import benchmark, validate


@click.group()
def connectors() -> None:
    """Develop and inspect local connector behavior."""
    pass


connectors.add_command(validate)
connectors.add_command(benchmark)


__all__ = ["connectors"]
