# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte local debug` commands.

The commands below are regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/local/debug.md
   :start-line: 2
"""

from __future__ import annotations

from typing import Annotated

from cyclopts import Parameter

from airbyte.cli._base import _create_app
from airbyte.cli.local._cli import local_app
from airbyte.cli.pyab import destination_smoke_test


debug_app = _create_app(name="debug", help_text="Run local debugging workflows.")
destinations_app = _create_app(name="destinations", help_text="Debug local destination behavior.")
local_app.command(debug_app)
debug_app.command(destinations_app)


@destinations_app.command(name="smoke-test")
def smoke_test(  # noqa: PLR0913
    *,
    destination: Annotated[str, Parameter(help="The destination connector to test.")],
    config: Annotated[
        str | None, Parameter(help="Destination configuration file or inline YAML.")
    ] = None,
    pip_url: Annotated[
        str | None, Parameter(help="Optional pip URL for Python destinations.")
    ] = None,
    use_python: Annotated[str | None, Parameter(help="Python interpreter specification.")] = None,
    scenarios: Annotated[str, Parameter(help="Smoke test scenarios to run.")] = "fast",
    custom_scenarios: Annotated[
        str | None,
        Parameter(help="Path to a JSON or YAML file containing additional scenarios."),
    ] = None,
    namespace_suffix: Annotated[
        str | None, Parameter(help="Suffix for the generated namespace.")
    ] = None,
    reuse_namespace: Annotated[str | None, Parameter(help="Existing namespace to reuse.")] = None,
    skip_preflight: Annotated[bool, Parameter(help="Skip the automatic preflight check.")] = False,
) -> None:
    """Run a local destination smoke test."""
    destination_smoke_test(
        destination=destination,
        config=config,
        pip_url=pip_url,
        use_python=use_python,
        scenarios=scenarios,
        custom_scenarios=custom_scenarios,
        namespace_suffix=namespace_suffix,
        reuse_namespace=reuse_namespace,
        skip_preflight=skip_preflight,
    )


__all__ = ["debug_app", "destinations_app"]
