# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte local debug` commands.

The commands below are regenerated by `poe docs-generate` from the Click command
tree; see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/local/debug.md
   :start-line: 2
"""

from __future__ import annotations

import click

from airbyte.cli.pyab import destination_smoke_test


@click.group()
def debug() -> None:
    """Debug local connector workflows."""
    pass


@debug.group()
def destinations() -> None:
    """Debug destination behavior with synthetic records."""
    pass


destinations.add_command(destination_smoke_test, name="smoke-test")


__all__ = ["debug"]
