# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte local sync` command.

The command below is regenerated by `poe docs-generate` from the Click command
tree; see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/local/sync.md
   :start-line: 2
"""

from __future__ import annotations

from airbyte.cli.pyab import sync


__all__ = ["sync"]
