# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte local sync` CLI reference.

The command below is regenerated by `poe docs-generate` from the Click command
tree; see `docs/generate_cli.py`.

.. include:: ../../../docs/generated/cli/local/sync.md
   :start-line: 2
"""

from __future__ import annotations


__all__: list[str] = []
