# Copyright (c) 2024 Airbyte, Inc., all rights reserved.
"""`airbyte local sync` command.

The command below is regenerated by `poe docs-generate` from the Cyclopts app;
see `docs/generate_cli_docs.py`.

.. include:: ../../../docs/generated/cli/local/sync.md
   :start-line: 2
"""

from __future__ import annotations

from typing import Annotated

from cyclopts import Parameter

from airbyte.cli.local._cli import local_app
from airbyte.cli.pyab import sync as run_sync


@local_app.command
def sync(
    *,
    source: Annotated[str, Parameter(help="The source connector to read from.")],
    destination: Annotated[str, Parameter(help="The destination connector to write to.")],
    source_config: Annotated[
        str | None, Parameter(name="--Sconfig", help="Source config file or inline YAML.")
    ] = None,
    source_pip_url: Annotated[
        str | None, Parameter(name="--Spip-url", help="Optional source pip URL.")
    ] = None,
    destination_config: Annotated[
        str | None, Parameter(name="--Dconfig", help="Destination config file or inline YAML.")
    ] = None,
    destination_pip_url: Annotated[
        str | None, Parameter(name="--Dpip-url", help="Optional destination pip URL.")
    ] = None,
    streams: Annotated[str | None, Parameter(help="Comma-separated stream names to read.")] = None,
    use_python: Annotated[str | None, Parameter(help="Python interpreter specification.")] = None,
) -> None:
    """Run a local full-refresh source-to-destination sync."""
    run_sync(
        source=source,
        source_config=source_config,
        source_pip_url=source_pip_url,
        destination=destination,
        destination_config=destination_config,
        destination_pip_url=destination_pip_url,
        streams=streams,
        use_python=use_python,
    )


__all__ = ["sync"]
