[tool.poe.tasks.wrkflw]
help = "Run wrkflw commands with automatic brew installation if needed"
shell = """
if ! command -v wrkflw &> /dev/null; then
  echo "Installing wrkflw via brew..."
  brew install wrkflw
fi
wrkflw "$@"
"""

[tool.poe.tasks.ci-test]
help = "Run wrkflw (opens TUI if no args provided)"
shell = """
if ! command -v wrkflw &> /dev/null; then
  echo "Installing wrkflw via brew..."
  brew install wrkflw
fi
wrkflw
"""

[tool.poe.tasks.ci-test-workflow]
help = "Run a GitHub Actions workflow locally (e.g., poe ci-test-workflow python_lint.yml)"
shell = """
if ! command -v wrkflw &> /dev/null; then
  echo "Installing wrkflw via brew..."
  brew install wrkflw
fi
wrkflw run --runtime emulation .github/workflows/${workflow}
"""
args = [
  { name = "workflow", positional = true, help = "Workflow filename (e.g., python_lint.yml)" }
]

[tool.poe.tasks.ci-validate]
help = "Validate a GitHub Actions workflow file (e.g., poe ci-validate python_lint.yml)"
shell = """
if ! command -v wrkflw &> /dev/null; then
  echo "Installing wrkflw via brew..."
  brew install wrkflw
fi
wrkflw validate .github/workflows/${workflow}
"""
args = [
  { name = "workflow", positional = true, help = "Workflow filename (e.g., python_lint.yml)" }
]
