# This file defines lint exceptions for pytest tests and examples.
# The 'tests' and 'examples' directories can both share this same exception list.

[tool.ruff]
preview = true

[tool.ruff.lint]
extend-ignore = [
    "ANN201",  # Type annotations not required for test functions
    "F841",    # Allow assignments that are not referenced
    "SLF001",  # Accessing private members ok for tests
    "DTZ005",  # Don't require timezone-aware datetimes for tests
]
