name: On-Demand GitHub Actions Pin Fix

on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR Number'
        type: string
        required: true
      comment-id:
        description: 'Comment ID (Optional)'
        type: string
        required: false

permissions:
  contents: write
  workflows: write
  pull-requests: write

env:
  AIRBYTE_ANALYTICS_ID: ${{ vars.AIRBYTE_ANALYTICS_ID }}

jobs:
  gh-ci-fix:
    name: Pin GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate as GitHub App
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: get-app-token
        with:
          owner: "airbytehq"
          repositories: "PyAirbyte"
          app-id: ${{ secrets.OCTAVIA_BOT_APP_ID }}
          private-key: ${{ secrets.OCTAVIA_BOT_PRIVATE_KEY }}

      - name: Run Poe Command
        uses: aaronsteers/poe-command-processor@v1
        with:
          command: "gh-ci-fix"
          github-token: ${{ steps.get-app-token.outputs.token }}
          pr: ${{ github.event.inputs.pr }}
          comment-id: ${{ github.event.inputs.comment-id }}
