name: Pytest (Fast-Fail)

on:
    push:
      branches:
      - main
    pull_request: {}

jobs:
  pytest-fast:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: "1.7.1"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install

    - name: Run Pytest
      run: poetry run pytest -m "not slow" --fast-fail
