name: "Verify Semantic PR Title"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

env:
  AIRBYTE_ANALYTICS_ID: ${{ vars.AIRBYTE_ANALYTICS_ID }}

permissions:
  pull-requests: read

jobs:
  validate_pr_title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        if: ${{ github.event.pull_request.draft == false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          # See: https://github.com/commitizen/conventional-commit-types/blob/master/index.json
          types: |
            Fix
            Feat
            Docs
            CI
            Chore
            Build
            Test

          # # We don't use scopes as of now
          # scopes: |
          #   core
          #   ui
          #   JIRA-\d+

          # Require capitalization for the first letter of the subject.
          subjectPattern: ^[A-Z].*$
          # The variables `subject` and `title` can be used within the message.
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            start with an uppercase character.
