name: Community PR Welcome Message

# This workflow automatically adds a welcome message to PRs from community contributors (forks)
# It includes PyAirbyte usage instructions and other helpful resources for testing changes
#
# MANUAL TESTING INSTRUCTIONS:
# To manually test this workflow, temporarily uncomment the "synchronize" event type as a workflow trigger.
# Then the workflow will run for all new commits.
#
# Before merging, remember to again comment-out the "synchronize" clause and uncomment the `if:` condition.

on:
  pull_request_target:
    types:
      - opened
      - reopened
      # Toggle this line, uncommenting for testing:
      # - synchronize

jobs:
  welcome-contributor:
    name: PR Welcome Message
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Resolve workflow variables
        id: vars
        uses: aaronsteers/resolve-ci-vars-action@2e56afab0344bbe03c047dfa39bae559d0291472 # v0.1.6

      - name: Render template
        id: template
        uses: chuhlomin/render-template@807354a04d9300c9c2ac177c0aa41556c92b3f75 # v1.10
        with:
          # Use a different template for internal vs forks (community)
          template: ${{ steps.vars.outputs.pr-source-is-fork == 'true' && '.github/pr-welcome-community.md' || '.github/pr-welcome-internal.md' }}
          vars: |
            repo_name: ${{ steps.vars.outputs.pr-source-repo-name-full }}
            branch_name: ${{ steps.vars.outputs.pr-source-git-branch }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.template.outputs.result }}
